-- AlterTable
ALTER TABLE `auction` ADD COLUMN `bidStep` INTEGER NOT NULL DEFAULT 1000,
    ADD COLUMN `binPrice` INTEGER NULL,
    ADD COLUMN `memberOnly` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `openBid` INTEGER NOT NULL DEFAULT 1000;
